# Generated by Django 5.0.7 on 2024-08-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classoptions',
            options={'verbose_name': 'Class Option', 'verbose_name_plural': 'Class Options'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Equipment Type', 'verbose_name_plural': 'Equipment Types'},
        ),
        migrations.AlterModelOptions(
            name='skillalias',
            options={'verbose_name_plural': 'Skill Aliases'},
        ),
        migrations.AlterModelOptions(
            name='skilldomain',
            options={'verbose_name': 'Skill Domain', 'verbose_name_plural': 'Skill Domains'},
        ),
        migrations.AlterModelOptions(
            name='skilloptions',
            options={'verbose_name': 'Skill Option', 'verbose_name_plural': 'Skill Options'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Skill Type', 'verbose_name_plural': 'Skill Types'},
        ),
        migrations.AlterField(
            model_name='classskills',
            name='alias',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_skill', to='rules_db.skillalias'),
        ),
        migrations.AlterField(
            model_name='classskills',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_db.classoptions'),
        ),
    ]
