# Generated by Django 5.0.7 on 2024-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classoptions',
            options={'verbose_name': 'Class Options', 'verbose_name_plural': 'Class Options'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Skill Type', 'verbose_name_plural': 'Skill Types'},
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='class_options',
            field=models.ManyToManyField(blank=True, help_text='Available class choices, i.e. casting source, subclass, etc.', related_name='character_classes', to='rules_db.classoptions'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='class_options_help',
            field=models.CharField(blank=True, help_text='A description of what the class options are for. Blank if n/a. Text is visible to players.', max_length=50, null=True),
        ),
    ]
