# Generated by Django 5.0.7 on 2024-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0002_alter_classoptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('HW', 'Weapon'), ('HS', 'Secondary'), ('AC', 'Accessory'), ('AR', 'Armor')], default='HW', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classskills',
            unique_together={('character_class', 'skill', 'alias')},
        ),
    ]
