# Generated by Django 5.0.7 on 2024-11-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0002_genericitem_consumable_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='time',
            field=models.DurationField(help_text='Standard activation time in minutes/seconds.', verbose_name='activation time'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='time',
            field=models.DurationField(help_text='Standard activation time in minutes/seconds.', verbose_name='activation time'),
        ),
    ]
