# Generated by Django 5.0.7 on 2024-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0004_alter_consumable_time_alter_ritual_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='allowed_equipment',
            field=models.ManyToManyField(help_text='Which types of equipment the material can be used to craft.', related_name='materials_allowed', to='rules_db.equipmenttype'),
        ),
    ]
