# Generated by Django 5.0.7 on 2024-10-22 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillalias',
            name='parent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_db.skill'),
        ),
    ]
