# Generated by Django 5.0.7 on 2024-11-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0005_alter_material_allowed_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('HW', 'Weapon'), ('HS', 'Secondary'), ('AC', 'Accessory'), ('AS', 'Armor (Slot)'), ('AW', 'Armor (Weight)')], max_length=2),
        ),
    ]
