# Generated by Django 5.0.7 on 2024-11-04 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0006_alter_equipmenttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_skill',
            field=models.ForeignKey(blank=True, help_text='The skill granted by the item, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to='rules_db.skill', verbose_name='skill'),
        ),
    ]
