# Generated by Django 5.0.7 on 2024-10-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0006_alter_characterclass_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exaltedskill',
            name='exalted_type',
            field=models.CharField(choices=[('EP', 'Exalted Passive'), ('ES', 'Exalted Slot')], default='EP', max_length=2, verbose_name='exalted skill type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exaltedskill',
            name='criteria',
            field=models.TextField(help_text='The full text of requirements to be met before the skill can be learned.', verbose_name='unlock criteria'),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='ability_type',
            field=models.CharField(choices=[('PS', 'Passive'), ('PF', 'Proficiency'), ('PG', 'Paragon')], help_text='Passives are learned only once; proficiencies stack.', max_length=2, verbose_name='passive type'),
        ),
        migrations.AlterField(
            model_name='slotskill',
            name='ability_type',
            field=models.CharField(choices=[('S', 'Spell'), ('T', 'Talent')], max_length=1, verbose_name='slot type'),
        ),
    ]
