# Generated by Django 5.0.7 on 2024-11-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0007_material_material_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='types',
        ),
    ]
