# Generated by Django 5.0.7 on 2024-11-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0009_alter_equipmenttype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleschapter',
            name='category',
        ),
    ]
