# Generated by Django 5.0.7 on 2024-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_db', '0010_remove_ruleschapter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleschapter',
            name='slug',
            field=models.SlugField(default='default', max_length=30, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
