# Generated by Django 5.0.7 on 2024-11-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('rules_db', '0012_alter_rulesarticle_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='long_description',
            field=models.OneToOneField(blank=True, help_text='Long form description for the class page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articlecontent'),
        ),
    ]
