# Generated by Django 5.0.7 on 2024-08-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Article Tag', 'verbose_name_plural': 'Article Tags'},
        ),
    ]
