# Generated by Django 5.0.7 on 2024-07-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('build_total', models.IntegerField(default=50)),
                ('character_classes', models.ManyToManyField(to='anoch_db.characterclass')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.player')),
                ('skills', models.ManyToManyField(to='anoch_db.skill')),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skills',
            field=models.ManyToManyField(to='anoch_db.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='types',
            field=models.ManyToManyField(to='anoch_db.type'),
        ),
    ]
