# Generated by Django 5.0.7 on 2024-07-19 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('D', 'Database'), ('I', 'Info'), ('B', 'Blog')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('component_type', models.CharField(choices=[('BU', 'Unrefined (Basic)'), ('BR', 'Refined (Basic)'), ('BE', 'Equipment (Basic)'), ('RL', 'Lesser (Ritual)'), ('RG', 'Greater (Ritual)'), ('RU', 'Unique (Ritual)'), ('SP', 'Special')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('mechanics', models.TextField(help_text='The specific rules mechanics of the ability.')),
                ('cost', models.IntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('types', models.ManyToManyField(related_name='skills', to='anoch_db.type')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='NPCCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('rp_notes', models.TextField(blank=True, help_text='Optional notes on how to roleplay this NPC', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'skill Aliases',
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('body_points', models.IntegerField(default=0)),
                ('class_type', models.CharField(choices=[('B', 'Base Class'), ('M', 'Master Class'), ('E', 'Exalted Class'), ('S', 'Subclass'), ('C', 'Common/Background'), ('N', 'NPC Only')], max_length=1)),
                ('class_options_help', models.TextField(help_text='A description of what the class options choices are for.')),
                ('class_options', models.ManyToManyField(related_name='character_classes', to='anoch_db.classoptions')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.type')),
            ],
            options={
                'abstract': False,
            },
            bases=('anoch_db.type',),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('time', models.IntegerField(help_text='Standard activation time in minutes.')),
                ('mechanics', models.TextField(help_text='The specific rules mechanics of the item.')),
                ('components', models.ManyToManyField(to='anoch_db.component')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('types', models.ManyToManyField(related_name='consumables_of_type', to='anoch_db.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExaltedSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
                ('criteria_type', models.CharField(choices=[('Q', 'Quest'), ('A', 'Achievement')], max_length=1)),
                ('criteria', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
                ('ability_type', models.CharField(choices=[('PS', 'Passive'), ('PF', 'Proficiency'), ('PG', 'Paragon')], max_length=2)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.CreateModel(
            name='PeriodicSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.CreateModel(
            name='UniqueMechanic',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.CreateModel(
            name='ClassSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.characterclass')),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.classoptions')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.skill')),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_skill', to='anoch_db.skillalias')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skill List',
                'unique_together': {('character_class', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stacks', models.IntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.skill')),
            ],
        ),
        migrations.AddField(
            model_name='characterclass',
            name='skills',
            field=models.ManyToManyField(related_name='character_classes', through='anoch_db.ClassSkills', to='anoch_db.skill'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('mechanics', models.TextField(help_text='The specific rules mechanics of the item.')),
                ('allowed_equipment', models.ManyToManyField(related_name='materials_allowed', to='anoch_db.type')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('types', models.ManyToManyField(related_name='materials_of_type', to='anoch_db.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPCCategorySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.npccategory')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.skill')),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npc_skill', to='anoch_db.skillalias')),
            ],
        ),
        migrations.AddField(
            model_name='npccategory',
            name='skills',
            field=models.ManyToManyField(through='anoch_db.NPCCategorySkills', to='anoch_db.skill'),
        ),
        migrations.CreateModel(
            name='NPCCharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='A description of what the entry represents in-game.')),
                ('rp_notes', models.TextField(blank=True, help_text='Optional notes on how to roleplay this NPC', null=True)),
                ('categories', models.ManyToManyField(related_name='npc_cards', to='anoch_db.npccategory')),
                ('skills', models.ManyToManyField(to='anoch_db.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCCharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=2)),
                ('build_total', models.IntegerField(default=50)),
                ('name', models.CharField(max_length=80)),
                ('character_classes', models.ManyToManyField(to='anoch_db.characterclass')),
                ('skills', models.ManyToManyField(through='anoch_db.CharacterSkills', to='anoch_db.skill')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.race')),
            ],
        ),
        migrations.AddField(
            model_name='characterskills',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.pccharactercard'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='anoch_db.user')),
            ],
        ),
        migrations.AddField(
            model_name='skillalias',
            name='alias_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anoch_db.skilldomain'),
        ),
        migrations.AddField(
            model_name='race',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.species'),
        ),
        migrations.CreateModel(
            name='PrestigePoint',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
                ('max_purchases', models.IntegerField()),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige_points', to='anoch_db.skilloptions')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.CreateModel(
            name='SlotSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.skill')),
                ('rank', models.IntegerField()),
                ('ability_type', models.CharField(choices=[('S', 'Spell'), ('T', 'Talent')], max_length=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='anoch_db.skilldomain')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.skill',),
        ),
        migrations.AddField(
            model_name='pccharactercard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.player'),
        ),
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('exaltedskill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anoch_db.exaltedskill')),
                ('time', models.IntegerField(help_text='Standard activation time in minutes.')),
                ('duration', models.IntegerField(default=1, help_text='Duration in months, including the month it is cast.')),
                ('rank', models.IntegerField(default=0)),
                ('frequency', models.CharField(help_text="Format: Nx per XYZ. I.E.: '1x per event', '3x per period'", max_length=50)),
                ('components', models.ManyToManyField(to='anoch_db.component')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('anoch_db.exaltedskill', models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='pccharactercard',
            unique_together={('card_id', 'player')},
        ),
    ]
