# Generated by Django 5.0.7 on 2024-07-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoch_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='class_options_help',
            field=models.CharField(blank=True, help_text='A description of what the class options choices are for.', max_length=50, null=True),
        ),
    ]
