# Generated by Django 5.0.7 on 2024-07-15 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoch_db', '0003_remove_characterclass_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=50, null=True)),
                ('alias_description', models.TextField(null=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.characterclass')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anoch_db.skill')),
            ],
            options={
                'verbose_name_plural': 'skill Aliases',
            },
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='skill_list',
            field=models.ManyToManyField(related_name='character_classes', through='anoch_db.SkillAlias', to='anoch_db.skill'),
        ),
    ]
