# Generated by Django 5.0.7 on 2024-07-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anoch_db', '0003_rename_player_id_playercharactercard_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'Character classes'},
        ),
    ]
