# Generated by Django 5.0.7 on 2024-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anoch_db', '0004_skillalias_alter_characterclass_skill_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillalias',
            name='alias_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillalias',
            name='alias_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
