# Generated by Django 5.0.7 on 2024-08-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_db', '0001_initial'),
        ('core', '0001_initial'),
        ('rules_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_db.entry')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rules_db.entry',),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_db.entry')),
                ('species_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'OPT_Species',
                'verbose_name_plural': 'OPT_Species',
            },
            bases=('rules_db.entry',),
        ),
        migrations.AddField(
            model_name='characterskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_db.skill'),
        ),
        migrations.AddField(
            model_name='npccategoryskills',
            name='alias',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npc_skill', to='rules_db.skillalias'),
        ),
        migrations.AddField(
            model_name='npccategoryskills',
            name='npc_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_db.npccategory'),
        ),
        migrations.AddField(
            model_name='npccategoryskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_db.skill'),
        ),
        migrations.AddField(
            model_name='npccategory',
            name='skills',
            field=models.ManyToManyField(through='character_db.NPCCategorySkills', to='rules_db.skill'),
        ),
        migrations.AddField(
            model_name='npccharactercard',
            name='categories',
            field=models.ManyToManyField(related_name='npc_cards', to='character_db.npccategory'),
        ),
        migrations.AddField(
            model_name='npccharactercard',
            name='skills',
            field=models.ManyToManyField(to='rules_db.skill'),
        ),
        migrations.AddField(
            model_name='pccharactercard',
            name='character_classes',
            field=models.ManyToManyField(to='rules_db.characterclass'),
        ),
        migrations.AddField(
            model_name='pccharactercard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AddField(
            model_name='pccharactercard',
            name='skills',
            field=models.ManyToManyField(through='character_db.CharacterSkills', to='rules_db.skill'),
        ),
        migrations.AddField(
            model_name='characterskills',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_db.pccharactercard'),
        ),
        migrations.AddField(
            model_name='pccharactercard',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_db.race'),
        ),
        migrations.AddField(
            model_name='race',
            name='parent_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_db.species'),
        ),
        migrations.AlterUniqueTogether(
            name='pccharactercard',
            unique_together={('card_id', 'player')},
        ),
    ]
